// ─── User-supplied point (from CSV upload) ───

export interface UserPoint {
  lat: number;
  lng: number;
  name?: string;
  category?: string;
}

export interface UserPointConstraint {
  points: UserPoint[];
  mode: 'exclude' | 'include' | 'penalty';
  radiusM: number;
  radiusSource: 'user' | 'inferred';
  label: string;
}

// ─── Analysis Specification (output of prompt parser) ───

export interface ClassificationMeta {
  confidence: 'high' | 'medium' | 'low';
  matchedKeywords: string[];
  reasoning: string;
  score: number;
  source: 'llm' | 'local';
}

export interface AnalysisSpec {
  businessType: string;
  sectorId: string;
  geography: {
    city: string;
    country?: string;
    neighborhoods?: string[];
    anchor?: { lat: number; lng: number; label?: string };
  };
  constraints: SpatialConstraint[];
  userPointConstraints: UserPointConstraint[];
  hasUserPointReference: boolean;
  positiveCriteria: string[];
  negativeCriteria: string[];
  inferredWeights: Record<string, number>;
  resultCount: number;
  parsingNotes: string[];
  confidence: 'high' | 'medium' | 'low';
  classificationMeta?: ClassificationMeta;
}

export interface SpatialConstraint {
  type: 'proximity' | 'exclusion' | 'preference';
  target: string;
  osmTags: string[];
  distanceM?: number;
  direction: 'near' | 'away';
  hardRule: boolean;
  label: string;
}

// ─── MCDA Criteria (dynamic, directional) ───

export type CriterionDirection = 'positive' | 'negative';
export type EvidenceBasis =
  | 'osm-observed'        // OSM Overpass returned a positive count
  | 'osm-absent'          // OSM returned 0 — may be genuine absence or coverage gap
  | 'insufficient-data'   // No data available — layer excluded, NOT scored 0 or 10
  | 'osm-derived'         // Derived/computed from OSM signals
  | 'google-corroborated' // OSM sparse but Google Places confirms activity (score boosted)
  | 'constraint-rule'     // Hard exclusion rule result
  | 'template-default'    // Score from a profile template, not observed data
  | 'ai-generated';       // Score generated by AI without OSM evidence

export interface MCDACriteria {
  name: string;
  weight: number;
  score: number | null;        // null = insufficient data (layer excluded from composite)
  rawValue: number | null;
  direction: CriterionDirection;
  required?: boolean;          // hard-constraint layer
  justification: string;
  evidenceBasis: EvidenceBasis;
  osmQuery?: string;
}

// ─── Exclusion result ───

export interface ExclusionCheck {
  rule: string;
  passed: boolean;
  detail: string;
  evidenceBasis: EvidenceBasis;
}

// ─── Location data ───

export interface POI {
  lat: number;
  lng: number;
  name?: string;
  type: string;
}

export interface LocationData {
  name: string;
  lat: number;
  lng: number;
  mcda_score: number;
  criteria_breakdown: MCDACriteria[];
  exclusions: ExclusionCheck[];
  excluded: boolean;
  reasoning: string;
  osmSignals: Record<string, number>;
  pois: POI[];
  searchRadiusM: number;
  scoreWithheld?: boolean;     // composite not computable (required data missing)
  routeMetrics?: Record<string, RouteMetric>;  // computed network routing per constraint
  trafficContext?: { congestionRatio: number; label: string; note: string };
  // Spatial Reliability Upgrade v1.0.3 — deterministic geographic checks (optional)
  recommended?: boolean;           // passed hard constraints AND min viable score
  riverDistanceM?: number | null;  // metres to nearest water edge
  inWaterfrontCorridor?: boolean | null;
  buildabilityStatus?: 'viable' | 'weak' | 'excluded' | string;
  exclusionReasons?: string[];
  hardConstraintPass?: boolean;
  // v1.1.0 multi-dimensional scores
  relativeRankScore?: number;      // 0-10: percentile rank within this run
  absoluteViabilityScore?: number; // 0-10: archetype-benchmarked viability
  confidenceScore?: number;        // 0-10: data trustworthiness
  recommendationStatus?: 'RECOMMENDED' | 'CANDIDATE_ZONE' | 'WEAK_CANDIDATE' | 'RAW_DIAGNOSTIC' | 'EXCLUDED' | 'NO_RELIABLE_RECOMMENDATION';
  competitionCapped?: boolean;     // competition whitespace cap was applied
}

export interface RouteMetric {
  status: 'evaluated' | 'unavailable';
  target?: [number, number];
  straightLineM?: number | null;
  networkM?: number | null;
  travelMin?: number | null;
  crossesRailway?: boolean | null;
  passed?: boolean | null;
  reason?: string;
  mode?: 'walk' | 'drive';
  maxMinutes?: number | null;
  maxDistanceM?: number | null;
  required?: boolean;
}

// ─── Analysis Result ───

// ─── v2 engine map layers (conversational analyses only) ───

export interface HexGridCell {
  h3: string;
  score: number;            // 0-10 composite (Pass-A surface)
  excluded: boolean;
  boundary: [number, number][]; // [lat, lng] ring
  /** Per-factor 0-10, direction already applied (higher = more favorable for all). */
  layerScores?: Record<string, number>;
}

export interface CatchmentOutline {
  locationName: string;
  locationRank: number;
  layerId: string;
  layerName: string;
  mode: 'walk' | 'drive';
  minutes: number;
  polygon: [number, number][]; // [lat, lng] ring
}

export interface AnalysisCritique {
  verdict: 'reliable' | 'weak' | 'unreliable';
  headline: string;
  issues: string[];
  whatWouldStrengthen: string[];
  confidence: 'high' | 'medium' | 'low';
  model?: string;
  // v1.1.0 extended critic contract
  shouldWithholdRecommendations?: boolean;
  recommendationModeOverride?: 'candidate_zones' | 'raw_diagnostic' | 'no_reliable_recommendation' | null;
  downgrades?: string[];
  confidenceAdjustment?: number | null;
  requiredFixes?: string[];
  userFacingWarning?: string | null;
}

export interface FactorDataQuality {
  name: string;
  provider: string;
  weight: number;
  featureCount: number;
  lowCoverage: boolean;
  nonDiscriminating: boolean;
}

export interface AnalysisResult {
  summary: string;
  business_type: string;
  target_location: string;
  methodology: string;
  spec: AnalysisSpec;
  locations: LocationData[];
  grounding_sources: GroundingSource[];
  /** Present only for v2 conversational-engine analyses */
  hexGrid?: HexGridCell[];
  catchments?: CatchmentOutline[];
  /** Senior-consultant self-critique of the computed result (v2 only) */
  critique?: AnalysisCritique | null;
  dataQuality?: FactorDataQuality[];
  /** True when the critic judged the ranking unreliable → the UI withholds the
   * recommendation and shows the critic's reasons instead of a confident list. */
  recommendationWithheld?: boolean;
  // Spatial Reliability Upgrade v1.0.3 — new optional fields (frontend-safe)
  analysisStatus?: 'reliable' | 'weak' | 'unreliable' | 'insufficient_viable_land' | string;
  suggestions?: string[];                       // relaxations when viable land is insufficient
  maskStats?: Record<string, number>;           // how many hexes each safeguard removed
  studyAreaBoundary?: [number, number][];       // [lat,lng] ring for the AOI outline
  waterfront?: {
    isWaterfront: boolean;
    strictness?: string | null;
    corridorWidthM?: number | null;
    corridorSource?: string | null;
    clampedFromM?: number | null;
  } | null;
  // v1.1.0 universal suitability fields
  recommendationMode?: 'recommended_sites' | 'candidate_zones' | 'raw_diagnostic' | 'no_reliable_recommendation';
  siteClaimLevel?: 'parcel_site' | 'point_candidate' | 'micro_market_zone' | 'broad_area';
  archetypeKey?: string;
  outputCount?: {
    requestedTopNRaw?: number | null;
    topNResolved: number;
    topNReason?: string;
    outputCountWarning?: string | null;
  };
  // Phase 17 transparency fields
  criticEnabled?: boolean;                  // was the post-exec self-critique actually run?
  constraintEnforcementLevel?: 'advisory' | 'enforced';  // v1.1.0 = advisory; v1.2 = enforced
  untracedConstraints?: string[];           // hard constraint phrases not traced to a SpecV2 gate
}

export interface GroundingSource {
  title: string;
  uri: string;
  retrievedAt: string;
  reliability: string;
}

// ─── Analysis Request (from UI) ───

export interface AnalysisRequest {
  rawPrompt: string;
  resultCount?: number;
}

export interface AnalysisStatus {
  message: string;
  progress: number;
}

// ─── App state ───

export type AppMode = 'demo' | 'live';
export type HeatmapType = string | null;

export interface DemoScenario {
  id: string;
  businessType: string;
  city: string;
  label: string;
  description: string;
  icon: string;
  result: AnalysisResult;
}
