// ─── User-supplied point (from CSV upload) ───

export interface UserPoint {
  lat: number;
  lng: number;
  name?: string;
  category?: string;
}

export interface UserPointConstraint {
  points: UserPoint[];
  mode: 'exclude' | 'include' | 'penalty';
  radiusM: number;
  radiusSource: 'user' | 'inferred';
  label: string;
}

// ─── Analysis Specification (output of prompt parser) ───

export interface ClassificationMeta {
  confidence: 'high' | 'medium' | 'low';
  matchedKeywords: string[];
  reasoning: string;
  score: number;
  source: 'llm' | 'local';
}

export interface AnalysisSpec {
  businessType: string;
  sectorId: string;
  geography: {
    city: string;
    country?: string;
    neighborhoods?: string[];
    anchor?: { lat: number; lng: number; label?: string };
  };
  constraints: SpatialConstraint[];
  userPointConstraints: UserPointConstraint[];
  hasUserPointReference: boolean;
  positiveCriteria: string[];
  negativeCriteria: string[];
  inferredWeights: Record<string, number>;
  resultCount: number;
  parsingNotes: string[];
  confidence: 'high' | 'medium' | 'low';
  classificationMeta?: ClassificationMeta;
}

export interface SpatialConstraint {
  type: 'proximity' | 'exclusion' | 'preference';
  target: string;
  osmTags: string[];
  distanceM?: number;
  direction: 'near' | 'away';
  hardRule: boolean;
  label: string;
}

// ─── MCDA Criteria (dynamic, directional) ───

export type CriterionDirection = 'positive' | 'negative';
export type EvidenceBasis =
  | 'osm-observed'        // OSM Overpass returned a positive count
  | 'osm-absent'          // OSM returned 0 — may be genuine absence or coverage gap
  | 'insufficient-data'   // No data available — layer excluded, NOT scored 0 or 10
  | 'osm-derived'         // Derived/computed from OSM signals
  | 'google-corroborated' // OSM sparse but Google Places confirms activity (score boosted)
  | 'constraint-rule'     // Hard exclusion rule result
  | 'template-default'    // Score from a profile template, not observed data
  | 'ai-generated';       // Score generated by AI without OSM evidence

export interface MCDACriteria {
  name: string;
  weight: number;
  score: number | null;        // null = insufficient data (layer excluded from composite)
  rawValue: number | null;
  direction: CriterionDirection;
  required?: boolean;          // hard-constraint layer
  justification: string;
  evidenceBasis: EvidenceBasis;
  osmQuery?: string;
}

// ─── Exclusion result ───

export interface ExclusionCheck {
  rule: string;
  passed: boolean;
  detail: string;
  evidenceBasis: EvidenceBasis;
}

// ─── Location data ───

export interface POI {
  lat: number;
  lng: number;
  name?: string;
  type: string;
}

export interface LocationData {
  name: string;
  lat: number;
  lng: number;
  mcda_score: number;
  criteria_breakdown: MCDACriteria[];
  exclusions: ExclusionCheck[];
  excluded: boolean;
  reasoning: string;
  osmSignals: Record<string, number>;
  pois: POI[];
  searchRadiusM: number;
  scoreWithheld?: boolean;     // composite not computable (required data missing)
  routeMetrics?: Record<string, RouteMetric>;  // computed network routing per constraint
  trafficContext?: { congestionRatio: number; label: string; note: string };
  // Spatial Reliability Upgrade v1.0.3 — deterministic geographic checks (optional)
  recommended?: boolean;           // passed hard constraints AND min viable score
  riverDistanceM?: number | null;  // metres to nearest water edge
  inWaterfrontCorridor?: boolean | null;
  buildabilityStatus?: 'viable' | 'weak' | 'excluded' | string;
  exclusionReasons?: string[];
  hardConstraintPass?: boolean;
  // v1.1.0 multi-dimensional scores
  relativeRankScore?: number;      // 0-10: percentile rank within this run
  absoluteViabilityScore?: number; // 0-10: archetype-benchmarked viability
  confidenceScore?: number;        // 0-10: data trustworthiness
  recommendationStatus?: 'RECOMMENDED' | 'CANDIDATE_ZONE' | 'WEAK_CANDIDATE' | 'RAW_DIAGNOSTIC' | 'EXCLUDED' | 'NO_RELIABLE_RECOMMENDATION';
  competitionCapped?: boolean;
  // Phase 18 uploaded-candidates fields
  candidateSource?: 'uploaded_point' | 'h3_hex';
  uploadedPointId?: string;
  uploadedPointAttributes?: Record<string, unknown>;
  // v1.4.0 score display policy
  displayScore?: number;         // rounded to nearest 0.5
  scoreBand?: string;            // e.g. "6.5–7.5"
  scorePrecision?: 'screening_estimate';
  confidenceLabel?: 'High' | 'Medium' | 'Low';
  confidenceReasons?: string[];
  closeBandWarning?: boolean;    // candidates statistically indistinguishable
  // v1.4.0 constraint policy
  provisionalBadge?: string;
  provisionalReasons?: string[];
}

export interface RouteMetric {
  status: 'evaluated' | 'unavailable';
  target?: [number, number];
  straightLineM?: number | null;
  networkM?: number | null;
  travelMin?: number | null;
  crossesRailway?: boolean | null;
  passed?: boolean | null;
  reason?: string;
  mode?: 'walk' | 'drive';
  maxMinutes?: number | null;
  maxDistanceM?: number | null;
  required?: boolean;
}

// ─── Analysis Result ───

// ─── v2 engine map layers (conversational analyses only) ───

export interface HexGridCell {
  h3: string;
  score: number;            // 0-10 composite (Pass-A surface)
  excluded: boolean;
  boundary: [number, number][]; // [lat, lng] ring
  /** Per-factor 0-10, direction already applied (higher = more favorable for all). */
  layerScores?: Record<string, number>;
}

export interface CatchmentOutline {
  locationName: string;
  locationRank: number;
  layerId: string;
  layerName: string;
  mode: 'walk' | 'drive';
  minutes: number;
  polygon: [number, number][]; // [lat, lng] ring
}

export interface AnalysisCritique {
  verdict: 'reliable' | 'weak' | 'unreliable';
  headline: string;
  issues: string[];
  whatWouldStrengthen: string[];
  confidence: 'high' | 'medium' | 'low';
  model?: string;
  // v1.1.0 extended critic contract
  shouldWithholdRecommendations?: boolean;
  recommendationModeOverride?: 'candidate_zones' | 'raw_diagnostic' | 'no_reliable_recommendation' | null;
  downgrades?: string[];
  confidenceAdjustment?: number | null;
  requiredFixes?: string[];
  userFacingWarning?: string | null;
}

export interface FactorDataQuality {
  name: string;
  provider: string;
  weight: number;
  featureCount: number;
  lowCoverage: boolean;
  nonDiscriminating: boolean;
}

export interface AnalysisResult {
  summary: string;
  business_type: string;
  target_location: string;
  methodology: string;
  spec: AnalysisSpec;
  locations: LocationData[];
  grounding_sources: GroundingSource[];
  /** Present only for v2 conversational-engine analyses */
  hexGrid?: HexGridCell[];
  catchments?: CatchmentOutline[];
  /** Senior-consultant self-critique of the computed result (v2 only) */
  critique?: AnalysisCritique | null;
  dataQuality?: FactorDataQuality[];
  /** True when the critic judged the ranking unreliable → the UI withholds the
   * recommendation and shows the critic's reasons instead of a confident list. */
  recommendationWithheld?: boolean;
  // Spatial Reliability Upgrade v1.0.3 — new optional fields (frontend-safe)
  analysisStatus?: 'reliable' | 'weak' | 'unreliable' | 'insufficient_viable_land' | string;
  suggestions?: string[];                       // relaxations when viable land is insufficient
  maskStats?: Record<string, number>;           // how many hexes each safeguard removed
  studyAreaBoundary?: [number, number][];       // [lat,lng] ring for the AOI outline
  waterfront?: {
    isWaterfront: boolean;
    strictness?: string | null;
    corridorWidthM?: number | null;
    corridorSource?: string | null;
    clampedFromM?: number | null;
  } | null;
  // v1.1.0 universal suitability fields
  recommendationMode?: 'recommended_sites' | 'candidate_zones' | 'raw_diagnostic' | 'no_reliable_recommendation';
  siteClaimLevel?: 'parcel_site' | 'point_candidate' | 'micro_market_zone' | 'broad_area';
  archetypeKey?: string;
  outputCount?: {
    requestedTopNRaw?: number | null;
    topNResolved: number;
    topNReason?: string;
    outputCountWarning?: string | null;
  };
  // Phase 17 transparency fields
  criticEnabled?: boolean;
  constraintEnforcementLevel?: 'advisory' | 'enforced';
  untracedConstraints?: string[];
  // Phase 18 uploaded-candidates-only fields
  uploadedCandidatesOnly?: boolean;
  candidateSource?: 'uploaded_points' | 'h3_grid';
  uploadedCandidateCount?: number;
  rankedUploadedCandidateCount?: number;
  excludedUploadedCandidateCount?: number;
  uploadedCandidateWarnings?: string[];
  // v1.2.0 deterministic planning fields
  planningMode?: 'deterministic' | 'advisory';
  archetypeSource?: string;
  weightsSource?: string;
  llmRole?: 'explanation_only' | 'ambiguity_resolution' | 'advisory';
  planningFingerprint?: string;
  specFingerprint?: string;
  normalizedPrompt?: string;
  constraintEnforcementRecords?: Array<{
    rawText: string;
    enforcementLevel: 'hard_enforced' | 'partially_enforced' | 'advisory' | 'not_enforced';
    enforcementMechanism: string;
    blockingIfFailed: boolean;
  }>;
  llmSuggestedButNotApplied?: Array<{
    factorName: string;
    llmWeight: number;
    canonicalWeight: number;
    action: string;
  }>;
  relaxationOptions?: Array<{
    id: string;
    description: string;
    effort: string;
    riskOfWeakeningConstraint: string;
  }>;
  // v1.3.0 evidence trail
  evidenceTrail?: EvidenceTrail;
  // v1.4.0 reliability hardening fields
  constraintPolicy?: {
    constraintEnforcementLevel: 'verified' | 'provisional' | 'unverifiable' | 'failed';
    unverifiedHardConstraints: string[];
    failedHardConstraints: string[];
    provisionalReasons: string[];
    validationChecklist: Array<{
      item: string;
      status: 'verified' | 'unverifiable' | 'failed' | 'not_applicable' | 'partial' | 'required';
      detail: string;
    }>;
    clientReady: boolean;
    recommendationWithheldReason?: string | null;
    siteClaimLevel: 'micro_market_zone' | 'parcel' | 'building' | 'address';
    hasUnverifiableConstraints: boolean;
  };
  metroValidation?: {
    mode: 'static_verified' | 'osm_metro' | 'generic_station_fallback' | 'unavailable';
    stationCount: number;
    city?: string | null;
    confidence: 'high' | 'medium' | 'low';
    warning?: string | null;
  };
  dataCoverage?: {
    availableWeight: number;
    missingWeight: number;
    coverageRatio: number;
    missingCriticalLayers: string[];
    coveragePenalty: 'none' | 'medium' | 'high';
  };
  disclaimer?: string;
  activeJobId?: string;
}

// ─── v1.3.0 Evidence Trail ───────────────────────────────────────────────────

export interface ProviderQueryEvidence {
  provider: 'Google Places' | 'OSM Overpass' | 'ORS' | 'Internal' | 'Derived';
  queryPurpose: string;
  queryType: string;
  queryParamsPublic: Record<string, unknown>;
  secretFieldsRedacted: true;
  requestedAt: string;
  responseStatus: string;
  featureCount: number;
  cacheKey?: string | null;
  cacheHit?: boolean | null;
  durationMs?: number | null;
  warning?: string | null;
}

export interface CandidateFactorEvidence {
  candidateId: string;
  rawValue: number | string | null;
  rawCount?: number | null;
  normalizedScore: number | null;
  weightedScore: number | null;
  nearbyFeatureExamples?: Record<string, unknown>[];
  explanation: string;
  warning?: string | null;
}

export interface FactorEvidence {
  factorKey: string;
  displayName: string;
  weight: number;
  direction: 'positive' | 'negative';
  catchment: string;
  dataSources: string[];
  confidence: string;
  scoringCurve: string;
  rawValueDescription: string;
  normalizationMethod: string;
  missingDataPolicy: string;
  appliedToCandidates: CandidateFactorEvidence[];
}

export interface ConstraintCheckEvidence {
  constraintName: string;
  constraintType: string;
  passed: boolean | null;
  detail: string;
  enforcementLevel: string;
  evidenceBasis: string;
}

export interface CandidateEvidence {
  candidateId: string;
  rank?: number | null;
  label: string;
  centroid: { lat: number; lng: number };
  h3CellIds?: string[];
  recommendationStatus: string;
  totalScore: number | null;
  relativeRankScore?: number | null;
  absoluteViabilityScore?: number | null;
  confidenceScore?: number | null;
  factorBreakdown: CandidateFactorEvidence[];
  constraintChecks: ConstraintCheckEvidence[];
  exclusionReasons: string[];
  relaxationNeeded: boolean;
  caveats: string[];
}

export interface ExclusionEvidence {
  targetType: 'h3_cell' | 'candidate';
  targetId: string;
  exclusionType: string;
  enforcementLevel: string;
  source: string;
  reason: string;
  geometryHash?: string | null;
  affectedAreaPct?: number | null;
}

export interface ScoringEvidence {
  formulaDescription: string;
  totalWeight: number;
  totalPresentWeight: number;
  normalization: Record<string, unknown>[];
  tieBreakers: string[];
  missingDataHandling: string;
  confidenceMethod: string;
  recommendationStatusRules: Record<string, unknown>[];
  minViableScore?: number | null;
  viableCandidates: number;
}

export interface EvidenceTrail {
  evidenceVersion: string;
  analysisId: string;
  jobId: string;
  createdAt: string;
  appVersion: string;
  engineVersion: string;
  prompt: {
    rawPrompt: string;
    normalizedPrompt: string;
    followUpTurns: string[];
    planningFingerprint: string;
    specFingerprint?: string | null;
    archetypeKey: string;
    planningMode: string;
  };
  dataSnapshot: {
    snapshotId: string;
    snapshotCreatedAt: string;
    providerMode: 'live' | 'cached' | 'mocked';
    cacheHit: boolean;
    dataFreshnessWarnings: string[];
  };
  studyArea: {
    label: string;
    geometryType: string;
    geometryHash: string;
    h3Resolution: number;
    h3CellCountBeforeMasks: number;
    h3CellCountAfterMasks: number;
    bounds?: Record<string, number> | null;
  };
  providerQueries: ProviderQueryEvidence[];
  factors: FactorEvidence[];
  candidates: CandidateEvidence[];
  exclusions: ExclusionEvidence[];
  scoring: ScoringEvidence;
  recommendationSummary: {
    requestedTopN: number;
    resolvedTopN: number;
    validRecommendationCount: number;
    excludedCandidateCount: number;
    recommendationStatus: string;
    relaxationOptions: Record<string, unknown>[];
  };
  limitations: string[];
}

export interface GroundingSource {
  title: string;
  uri: string;
  retrievedAt: string;
  reliability: string;
}

// ─── Analysis Request (from UI) ───

export interface AnalysisRequest {
  rawPrompt: string;
  resultCount?: number;
}

export interface AnalysisStatus {
  message: string;
  progress: number;
}

// ─── App state ───

export type AppMode = 'demo' | 'live';
export type HeatmapType = string | null;

export interface DemoScenario {
  id: string;
  businessType: string;
  city: string;
  label: string;
  description: string;
  icon: string;
  result: AnalysisResult;
}
